name: West End Insurance
favicon: null
layout_spectrum: 0.74413
typography_spectrum: 0.1489362
title: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#cfcfcf'
    - '#3f3f3f'
    - '#6f6f6f'
  brandStrength: 0.625
  lightness: 0.6148936
  saturation: 0.8686305
  rhythmicContrast: 0.25
purpose: []
