name: wenashville
favicon: null
layout_spectrum: 0.98826
typography_spectrum: 0.74413
title: West End Insurance
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0c1417'
    - '#b3bfb1'
    - '#3a6a76'
    - '#cd9a5b'
    - '#914f2c'
  brandStrength: 0.43801802140660584
  lightness: 0.640558711020276
  saturation: 0.8686305209994316
  rhythmicContrast: 0.5052215792238712
purpose: []
